name: Publish Package

env:
  TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install setuptools wheel twine
    - name: Test
      run: |
        cd tests && python -m unittest -v test_rosmsg_dict_converter.py
      continue-on-error: false
    - name: Check environment variables
      run: |
        echo "TWINE_USERNAME is set: ${{ env.TWINE_USERNAME != '' }}"
        echo "TWINE_PASSWORD is set: ${{ env.TWINE_PASSWORD != '' }}"
    - name: Build and upload package
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}