name: Publish Package

env:
  TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        rosdistro: [noetic]
    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.rosdistro }}-ros-core
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang-format-10 file git python3-catkin-lint python3-pip python3-rosdep
        pip install setuptools wheel twine
    - name: Test
      run: |
        cd tests && python -m unittest -v test_rosmsg_dict_converter.py
      continue-on-error: false
    - name: Check environment variables
      run: |
        echo "TWINE_USERNAME is set: ${{ env.TWINE_USERNAME != '' }}"
        echo "TWINE_PASSWORD is set: ${{ env.TWINE_PASSWORD != '' }}"
    - name: Build and upload package
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}